import { useEffect, useState } from "react";
import { documentHealth } from "./api";
import type { Chat, DocumentHealth, DocumentInfo } from "./types";
import { useDialog } from "./useDialog";

export function ManualDialog({ documents, loading, error, onRefresh, onSelect, onOpen, onHealth, onRemove, onClose }: { documents: DocumentInfo[]; loading: boolean; error: string; onRefresh(): Promise<void>; onSelect(id: string): void; onOpen(id: string): void; onHealth(document: DocumentInfo): void; onRemove(document: DocumentInfo): void; onClose(): void }) {
  const dialogRef = useDialog<HTMLDivElement>(onClose); const [filter, setFilter] = useState(""); const normalized = filter.trim().toLowerCase();
  const visible = documents.filter((document) => !normalized || [document.title, document.brand, document.model, document.id, ...document.tags].join(" ").toLowerCase().includes(normalized));
  return <div className="modal-backdrop" role="presentation"><div ref={dialogRef} className="modal" role="dialog" aria-modal="true" aria-label="Manual library">
    <div className="modal-header"><div><h2>Manual library</h2><p>Select the manual used by the current chat.</p></div><button className="icon-button" onClick={onClose} aria-label="Close manual library">×</button></div>
    <label className="library-filter"><span className="sr-only">Filter manuals</span><input value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="Filter by title, brand, model, or tag" /></label>
    {loading && <div className="modal-status">Loading manuals…</div>}{error && <div className="message-error">{error} <button onClick={() => void onRefresh()}>Retry</button></div>}
    {!loading && !error && <div className="manual-list"><button className="manual-item" onClick={() => onSelect("")}><strong>All manuals</strong><span>Search every imported document</span></button>{visible.map((document) => <div className="manual-item" key={document.id}><strong>{document.title}</strong><div className="manual-metadata"><span><b>ID</b> {document.id}</span>{document.brand && <span><b>Brand</b> {document.brand}</span>}{document.model && <span><b>Model</b> {document.model}</span>}{document.tags.length > 0 && <span><b>Tags</b> {document.tags.join(", ")}</span>}</div><span>{document.chunk_count} chunks · {document.page_count} pages</span><div className="manual-actions"><button onClick={() => onSelect(document.id)}>Use in chat</button><button onClick={() => onOpen(document.id)}>Open manual</button><button onClick={() => onHealth(document)}>Health</button><button className="remove-manual" onClick={() => onRemove(document)}>Remove</button></div></div>)}{normalized && !visible.length && <div className="modal-status">No manuals match “{filter}”.</div>}</div>}
  </div></div>;
}

export function ConfirmDeleteChat({ chat, streaming, onCancel, onConfirm }: { chat: Chat; streaming: boolean; onCancel(): void; onConfirm(): void }) { const ref = useDialog<HTMLDivElement>(onCancel); return <div className="modal-backdrop"><div ref={ref} className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="delete-chat-title"><h2 id="delete-chat-title">Delete chat?</h2><p>“{chat.title}” and its messages will be permanently removed.{streaming ? " The active response will be stopped." : ""}</p><div className="confirm-actions"><button onClick={onCancel} autoFocus>Cancel</button><button className="danger-button" onClick={onConfirm}>Delete</button></div></div></div>; }

export function ConfirmDeleteDocument({ document, onCancel, onConfirm }: { document: DocumentInfo; onCancel(): void; onConfirm(): Promise<void> }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const ref = useDialog<HTMLDivElement>(onCancel, !busy);
  const remove = async () => { setBusy(true); setError(""); try { await onConfirm(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not remove manual"); setBusy(false); } };
  return <div className="modal-backdrop"><div ref={ref} className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="delete-document-title"><h2 id="delete-document-title">Remove manual?</h2><p>“{document.title}” and its indexed chunks and images will be permanently removed. Existing chats will switch to all manuals.</p>{error && <div className="message-error">{error}</div>}<div className="confirm-actions"><button onClick={onCancel} disabled={busy} autoFocus>Cancel</button><button className="danger-button" onClick={() => void remove()} disabled={busy}>{busy ? "Removing…" : "Remove"}</button></div></div></div>;
}

export function ConfirmScopeChange({ current, next, onCancel, onConfirm }: { current: string; next: string; onCancel(): void; onConfirm(): void }) { const ref = useDialog<HTMLDivElement>(onCancel); return <div className="modal-backdrop"><div ref={ref} className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="scope-change-title"><h2 id="scope-change-title">Change manual scope?</h2><p>This chat currently uses {current}. Switching to {next} changes the sources used for future answers but does not change earlier responses.</p><div className="confirm-actions"><button onClick={onCancel} autoFocus>Cancel</button><button onClick={onConfirm}>Change scope</button></div></div></div>; }

export function DocumentHealthDialog({ document, onClose, onSettings }: { document: DocumentInfo; onClose(): void; onSettings(): void }) {
  const [health, setHealth] = useState<DocumentHealth | null>(null); const [error, setError] = useState(""); const ref = useDialog<HTMLDivElement>(onClose);
  useEffect(() => { let active = true; documentHealth(document.id).then((value) => { if (active) setHealth(value); }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : "Could not load document health"); }); return () => { active = false; }; }, [document.id]);
  const state = (coverage: { complete: boolean; total: number }) => coverage.total === 0 ? "Empty" : coverage.complete ? "Healthy" : "Incomplete";
  return <div className="modal-backdrop"><div ref={ref} className="modal health-dialog" role="dialog" aria-modal="true" aria-labelledby="health-title"><div className="modal-header"><div><h2 id="health-title">Document health</h2><p>{document.title}</p></div><button className="icon-button" onClick={onClose} aria-label="Close document health">×</button></div>{!health && !error && <div className="modal-status">Checking document…</div>}{error && <div className="message-error">{error}</div>}{health && <><div className="health-counts"><div><strong>{health.chunk_count}</strong><span>Chunks</span></div><div><strong>{health.image_count}</strong><span>Images</span></div></div><div className="health-index"><div><strong>Full-text index</strong><span>{state(health.fts)} · {health.fts.indexed}/{health.fts.total} chunks</span></div><div><strong>Vector index</strong><span>{!health.vectors.configured ? "Not configured" : health.vectors.stale ? `Stale · ${health.vectors.indexed}/${health.vectors.total} chunks` : `${state(health.vectors)} · ${health.vectors.indexed}/${health.vectors.total} chunks`}</span></div></div><section className="health-warnings"><h3>Import warnings</h3>{health.warnings.length ? <ul>{health.warnings.map((warning, index) => <li key={`${warning.code}-${warning.line || 0}-${index}`}>{warning.line ? `Line ${warning.line}: ` : ""}{warning.message}</li>)}</ul> : <p>No import warnings.</p>}</section><div className="modal-footer"><button className="secondary-button" onClick={onSettings}>Open settings</button><button onClick={onClose}>Done</button></div></>}</div></div>;
}
