import { useEffect, useState } from "react";
import { buildEmbeddingIndex, embeddingIndexStatus, getSettings, saveSettings, testSettings } from "./api";
import type { EmbeddingIndexStatus, Settings } from "./types";
import { useDialog } from "./useDialog";

export function SettingsDialog({ onClose, onNotify, onChanged }: { onClose(): void; onNotify(message: string): void; onChanged(): void }) {
  const [value, setValue] = useState<Settings | null>(null); const [index, setIndex] = useState<EmbeddingIndexStatus | null>(null);
  const [savedValue, setSavedValue] = useState<Settings | null>(null);
  const [status, setStatus] = useState("Loading…"); const [busy, setBusy] = useState(false);
  const refresh = async () => { try { const [settings, indexStatus] = await Promise.all([getSettings(), embeddingIndexStatus()]); setValue(settings); setSavedValue(settings); setIndex(indexStatus); setStatus(""); } catch (error) { setStatus(error instanceof Error ? error.message : "Could not load settings"); } };
  useEffect(() => void refresh(), []);
  const dirty = !!value && !!savedValue && JSON.stringify(value) !== JSON.stringify(savedValue);
  const requestClose = () => { if (!dirty || window.confirm("Discard unsaved settings changes?")) onClose(); };
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
  const dialogRef = useDialog<HTMLDivElement>(requestClose, !busy);
  if (!value) return <div className="modal-backdrop"><div ref={dialogRef} className="modal" role="dialog" aria-modal="true" aria-label="Settings"><div className="modal-header"><h2>Settings</h2><button className="icon-button" onClick={onClose} aria-label="Close settings">×</button></div><p>{status}</p></div></div>;
  const changeProvider = (field: string, fieldValue: string) => setValue({ ...value, provider: { ...value.provider, [field]: fieldValue } });
  const changeEmbedding = (field: string, fieldValue: string | number) => setValue({ ...value, embedding: { ...value.embedding, [field]: fieldValue } });
  const save = async () => { setBusy(true); try { const saved = await saveSettings(value); setValue(saved); setSavedValue(saved); setStatus("Settings saved"); onNotify("Settings saved"); onChanged(); setIndex(await embeddingIndexStatus()); } catch (error) { setStatus(error instanceof Error ? error.message : "Save failed"); } finally { setBusy(false); } };
  const test = async (target: "provider" | "embedding") => { setBusy(true); try { const result = await testSettings(target, value); setStatus(`${target} connection OK: ${result.model}${result.dimensions ? ` (${result.dimensions} dimensions)` : ""}`); onNotify(`${target === "provider" ? "Chat" : "Embedding"} connection succeeded`); } catch (error) { setStatus(error instanceof Error ? error.message : "Test failed"); } finally { setBusy(false); } };
  const build = async () => { if (dirty) { setStatus("Save settings before building embeddings"); return; } setBusy(true); try { const result = await buildEmbeddingIndex((indexed, total) => setStatus(`Embedding ${indexed}/${total} chunks…`)); setIndex(result); setStatus("Embedding index complete"); onNotify("Embedding index complete"); onChanged(); } catch (error) { setStatus(error instanceof Error ? error.message : "Index build failed"); } finally { setBusy(false); } };
  return <div className="modal-backdrop"><div ref={dialogRef} className="modal settings-modal" role="dialog" aria-modal="true" aria-label="Provider settings"><div className="modal-header"><div><h2>Provider settings</h2><p>Saved to config.toml. Environment variables override these values. Embeddings are optional and improve search quality.</p></div><button className="icon-button" onClick={requestClose} disabled={busy} aria-label="Close settings">×</button></div>
    <div className="settings-sections">
      <fieldset><legend>Chat provider</legend><label>Base URL<input value={value.provider.base_url} onChange={(event) => changeProvider("base_url", event.target.value)} /></label><label>Model<input value={value.provider.model} onChange={(event) => changeProvider("model", event.target.value)} /></label><label>Timeout<input value={value.provider.timeout} onChange={(event) => changeProvider("timeout", event.target.value)} /></label><KeyFields settings={value.provider} change={changeProvider} /><button onClick={() => void test("provider")} disabled={busy}>Test chat connection</button></fieldset>
      <fieldset><legend>Embedding provider</legend><label>Base URL<input value={value.embedding.base_url} onChange={(event) => changeEmbedding("base_url", event.target.value)} /></label><label>Model<input value={value.embedding.model} onChange={(event) => changeEmbedding("model", event.target.value)} /></label><div className="settings-grid"><label>Dimensions<input type="number" value={value.embedding.dimensions} onChange={(event) => changeEmbedding("dimensions", Number(event.target.value))} /></label><label>Batch size<input type="number" value={value.embedding.batch_size} onChange={(event) => changeEmbedding("batch_size", Number(event.target.value))} /></label></div><label>Query instruction<textarea value={value.embedding.query_instruction} onChange={(event) => changeEmbedding("query_instruction", event.target.value)} /></label><KeyFields settings={value.embedding} change={changeEmbedding} /><button onClick={() => void test("embedding")} disabled={busy}>Test embedding connection</button></fieldset>
    </div>
    {value.environment_overrides.length > 0 && <p className="settings-warning">Environment overrides: {value.environment_overrides.join(", ")}</p>}
    <div className="index-status"><strong>Vector index</strong><span>{index?.building ? `Building · ${index.progress_indexed || 0}/${index.progress_total || index.total}` : index?.complete ? `${index.indexed}/${index.total} chunks indexed` : `Stale · ${index?.indexed || 0}/${index?.total || 0}`}</span><button onClick={() => void build()} disabled={busy || dirty} title={dirty ? "Save settings before building embeddings" : undefined}>{index?.building ? "View progress" : "Build embeddings"}</button></div>
    {status && <p className="modal-status">{status}</p>}<div className="modal-footer"><span>{dirty ? "Unsaved changes · " : ""}Keys are never returned by the API.</span><button onClick={() => void save()} disabled={busy || !dirty}>Save settings</button></div>
  </div></div>;
}

function KeyFields({ settings, change }: { settings: { api_key?: string; api_key_set: boolean; api_key_action?: string }; change(field: string, value: string): void }) {
  return <div className="key-fields"><label>API key action<select value={settings.api_key_action || "preserve"} onChange={(event) => change("api_key_action", event.target.value)}><option value="preserve">Preserve {settings.api_key_set ? "saved key" : "empty key"}</option><option value="replace">Replace key</option><option value="clear">Clear key</option></select></label>{settings.api_key_action === "replace" && <label>New API key<input type="password" value={settings.api_key || ""} onChange={(event) => change("api_key", event.target.value)} /></label>}</div>;
}
